package com.example.model

object UnilogKnowledgeBase {

    // Approved Unit of Measure mappings (from Unilog Master UOM Standards)
    val UOM_MAPPINGS = mapOf(
        "inches" to "in",
        "inch" to "in",
        "in." to "in",
        "\"" to "in",
        "feet" to "ft",
        "foot" to "ft",
        "ft." to "ft",
        "'" to "ft",
        "pounds" to "lb",
        "lbs" to "lb",
        "lbs." to "lb",
        "psi" to "psi",
        "#" to "lb Class",
        "volts" to "V",
        "volt" to "V",
        "v" to "V",
        "amps" to "A",
        "amp" to "A",
        "amperes" to "A",
        "dba" to "dBA",
        "decibels" to "dBA",
        "gpm" to "gpm",
        "gallons per minute" to "gpm",
        "rpm" to "rpm",
        "deg f" to "°F",
        "deg c" to "°C",
        "mm" to "mm",
        "cm" to "cm",
        "cf" to "cu-ft",
        "ga" to "ga"
    )

    // Decimal to Fraction conversions (from Decimal_Fraction.xlsx)
    val DECIMAL_FRACTION_LOOKUP = listOf(
        0.015625 to "1/64",
        0.03125 to "1/32",
        0.046875 to "3/64",
        0.0625 to "1/16",
        0.078125 to "5/64",
        0.09375 to "3/32",
        0.109375 to "7/64",
        0.125 to "1/8",
        0.140625 to "9/64",
        0.15625 to "5/32",
        0.171875 to "11/64",
        0.1875 to "3/16",
        0.203125 to "13/64",
        0.21875 to "7/32",
        0.234375 to "15/64",
        0.25 to "1/4",
        0.265625 to "17/64",
        0.28125 to "9/32",
        0.296875 to "19/64",
        0.3125 to "5/16",
        0.328125 to "21/64",
        0.34375 to "11/32",
        0.359375 to "23/64",
        0.375 to "3/8",
        0.390625 to "25/64",
        0.40625 to "13/32",
        0.421875 to "27/64",
        0.4375 to "7/16",
        0.453125 to "29/64",
        0.46875 to "15/32",
        0.484375 to "31/64",
        0.5 to "1/2",
        0.515625 to "33/64",
        0.53125 to "17/32",
        0.546875 to "35/64",
        0.5625 to "9/16",
        0.578125 to "37/64",
        0.59375 to "19/32",
        0.609375 to "39/64",
        0.625 to "5/8",
        0.640625 to "41/64",
        0.65625 to "21/32",
        0.671875 to "43/64",
        0.6875 to "11/16",
        0.703125 to "45/64",
        0.71875 to "23/32",
        0.734375 to "47/64",
        0.75 to "3/4",
        0.765625 to "49/64",
        0.78125 to "25/32",
        0.796875 to "51/64",
        0.8125 to "13/16",
        0.828125 to "53/64",
        0.84375 to "27/32",
        0.859375 to "55/64",
        0.875 to "7/8",
        0.890625 to "57/64",
        0.90625 to "29/32",
        0.921875 to "59/64",
        0.9375 to "15/16",
        0.953125 to "61/64",
        0.96875 to "31/32",
        0.984375 to "63/64"
    )

    // Common Industrial Jargon & Abbreviations
    val ABBREVIATIONS = mapOf(
        "CPLG" to "Coupling",
        "BRS" to "Brass",
        "SS" to "Stainless Steel",
        "SST" to "Stainless Steel",
        "BSS" to "Black Stainless Steel",
        "BK" to "Black",
        "WH" to "White",
        "NPT" to "NPT",
        "MNPT" to "Male NPT",
        "FNPT" to "Female NPT",
        "GALV" to "Galvanized",
        "VLV" to "Valve",
        "FLG" to "Flange",
        "ELL" to "Elbow",
        "TEE" to "Tee",
        "RED" to "Reducer",
        "ADPT" to "Adapter",
        "HYD" to "Hydraulic",
        "PEX" to "PEX",
        "PVC" to "PVC",
        "CPVC" to "CPVC",
        "STL" to "Steel",
        "CI" to "Cast Iron",
        "DI" to "Ductile Iron",
        "BLW" to "Blower",
        "MTR" to "Motor",
        "CMPR" to "Compressor",
        "STR" to "Straight",
        "BLTLN" to "Built-In",
        "CIRC" to "Circular"
    )

    // Canonical Brand & Manufacturer Lookups (UniCat 27,000+ entries)
    val CANONICAL_BRANDS = mapOf(
        "frigidaire" to Triple("FRIGIDAIRE®", "Electrolux Home Products Inc", "FRIG"),
        "whirlpool" to Triple("Whirlpool®", "Whirlpool Corporation", "WHIR"),
        "ge" to Triple("GE Appliances®", "Haier US Appliance Solutions Inc", "GEAP"),
        "general electric" to Triple("GE Appliances®", "Haier US Appliance Solutions Inc", "GEAP"),
        "kitchenaid" to Triple("KitchenAid®", "Whirlpool Corporation", "KTCH"),
        "kitchen aid" to Triple("KitchenAid®", "Whirlpool Corporation", "KTCH"),
        "lg" to Triple("LG®", "LG Electronics USA Inc", "LGEL"),
        "speed queen" to Triple("Speed Queen®", "Alliance Laundry Systems LLC", "SPDQ"),
        "diablo" to Triple("Diablo®", "Freud America Inc", "DIAB"),
        "freud" to Triple("Freud®", "Freud America Inc", "FREU"),
        "3m" to Triple("3M®", "3M Company", "3MCO"),
        "mirka" to Triple("Mirka®", "Mirka Abrasives Inc", "MIRK"),
        "milwaukee" to Triple("Milwaukee®", "Milwaukee Electric Tool Corp.", "MILW"),
        "milw" to Triple("Milwaukee®", "Milwaukee Electric Tool Corp.", "MILW"),
        "dewalt" to Triple("DEWALT®", "Black & Decker Inc.", "DEWA"),
        "makita" to Triple("Makita®", "Makita U.S.A. Inc.", "MAKI"),
        "kreg" to Triple("Kreg®", "Kreg Tool Company", "KREG"),
        "trex" to Triple("Trex®", "Trex Company Inc.", "TREX"),
        "timbertech" to Triple("TimberTech®", "The AZEK Company Inc.", "TIMB"),
        "azek" to Triple("AZEK®", "The AZEK Company Inc.", "AZEK"),
        "rheem" to Triple("Rheem®", "Rheem Manufacturing Company", "RHEE"),
        "kohler" to Triple("KOHLER®", "Kohler Co.", "KOHL"),
        "moen" to Triple("MOEN®", "Moen Incorporated", "MOEN"),
        "nibco" to Triple("NIBCO®", "NIBCO Inc.", "NIBC"),
        "charlotte pipe" to Triple("Charlotte Pipe®", "Charlotte Pipe and Foundry Company", "CHAR"),
        "charlotte" to Triple("Charlotte Pipe®", "Charlotte Pipe and Foundry Company", "CHAR"),
        "viega" to Triple("Viega®", "Viega LLC", "VIEG"),
        "watts" to Triple("WATTS®", "Watts Water Technologies Inc.", "WATT"),
        "parker" to Triple("Parker®", "Parker Hannifin Corporation", "PARK"),
        "eaton" to Triple("Eaton®", "Eaton Corporation plc", "EATN"),
        "square d" to Triple("Square D®", "Schneider Electric SE", "SQD"),
        "southwire" to Triple("Southwire®", "Southwire Company LLC", "SOUT"),
        "leviton" to Triple("Leviton®", "Leviton Manufacturing Co. Inc.", "LEVI"),
        "kichler" to Triple("Kichler®", "Kichler Lighting LLC", "KICH"),
        "satco" to Triple("Satco®", "Satco Products Inc.", "SATC"),
        "philips" to Triple("Philips®", "Signify North America Corporation", "PHIL")
    )

    val PLACEHOLDER_STRINGS = setOf(
        "-- Unbranded --",
        "-- No Unilog Brand --",
        "-- No DIB Brand --",
        "COMMODITY - UNBRANDED",
        "Unbranded",
        "Unknown",
        "N/A",
        "NA",
        "None",
        "-"
    )
}
